"""expand_schema_enterprise

Revision ID: 3c26f29328e5
Revises: d4ffa44920bd
Create Date: 2026-09-07 23:01:45.708681

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3c26f29328e5'
down_revision: Union[str, Sequence[str], None] = 'd4ffa44920bd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('enterprise_apis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('api_key_hash', sa.String(), nullable=False),
    sa.Column('label', sa.String(length=100), nullable=True),
    sa.Column('webhook_url', sa.Text(), nullable=True),
    sa.Column('total_calls', sa.Integer(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_enterprise_apis_api_key_hash'), 'enterprise_apis', ['api_key_hash'], unique=True)
    op.create_index(op.f('ix_enterprise_apis_id'), 'enterprise_apis', ['id'], unique=False)
    op.add_column('audit_logs', sa.Column('diarization_speakers', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('model_version', sa.String(length=60), nullable=True))
    op.add_column('audit_logs', sa.Column('inference_latency_ms', sa.Integer(), nullable=True))
    op.add_column('audit_logs', sa.Column('client_ip', sa.String(length=45), nullable=True))
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_index(op.f('ix_audit_logs_attempt_time'), 'audit_logs', ['attempt_time'], unique=False)
    op.add_column('enrollments', sa.Column('embedding_dim', sa.Integer(), nullable=True))
    op.add_column('enrollments', sa.Column('audio_quality_snr', sa.Float(), nullable=True))
    op.add_column('enrollments', sa.Column('status', sa.String(length=20), nullable=True))
    op.add_column('enrollments', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.add_column('users', sa.Column('full_name', sa.String(length=120), nullable=True))
    op.add_column('users', sa.Column('phone_number', sa.String(length=15), nullable=True))
    op.add_column('users', sa.Column('network_operator', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('imei', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'imei')
    op.drop_column('users', 'network_operator')
    op.drop_column('users', 'phone_number')
    op.drop_column('users', 'full_name')
    op.alter_column('enrollments', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('enrollments', 'updated_at')
    op.drop_column('enrollments', 'status')
    op.drop_column('enrollments', 'audio_quality_snr')
    op.drop_column('enrollments', 'embedding_dim')
    op.drop_index(op.f('ix_audit_logs_attempt_time'), table_name='audit_logs')
    op.alter_column('audit_logs', 'user_id',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('audit_logs', 'client_ip')
    op.drop_column('audit_logs', 'inference_latency_ms')
    op.drop_column('audit_logs', 'model_version')
    op.drop_column('audit_logs', 'diarization_speakers')
    op.drop_index(op.f('ix_enterprise_apis_id'), table_name='enterprise_apis')
    op.drop_index(op.f('ix_enterprise_apis_api_key_hash'), table_name='enterprise_apis')
    op.drop_table('enterprise_apis')
    # ### end Alembic commands ###
