"""swapped email for cnic

Revision ID: d4ffa44920bd
Revises: 97c026745830
Create Date: 2026-05-10 01:42:54.855641

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd4ffa44920bd'
down_revision: Union[str, Sequence[str], None] = '97c026745830'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('cnic', sa.String(), server_default='0000000000000', nullable=False))
    op.create_index(op.f('ix_users_cnic'), 'users', ['cnic'], unique=True)
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), server_default=sa.text("'legacy@awaaz.com'::character varying"), autoincrement=False, nullable=False))
    op.drop_index(op.f('ix_users_cnic'), table_name='users')
    op.drop_column('users', 'cnic')
    # ### end Alembic commands ###
